blank_issues_enabled: true

# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! If you haven't already, please be sure to check out [the contributing guidelines](https://github.com/ERNI-Academy/erni-academy-template/blob/main/CONTRIBUTING.md).
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! <br /> <br />We here at Erni-Academy are proud of you! :tada:<br /><br />If you're interested in tackling another bug or feature, take a look at the open issues, especially those labeled `help wanted`."
  
# It is recommend to include as many gifs and emojis as possible