name: allure-report
on:
  workflow_call:
      
      
jobs:
    allure:
        name: Generate Allure Report
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2 

          - name: Get Allure history
            uses: actions/checkout@v2
            if: always()
            continue-on-error: true
            with:
              ref: gh-pages
              path: gh-pages
              
          - uses: actions/download-artifact@v4
            with:
              pattern: allure-results-*
              path: allure-results
              merge-multiple: true

          - name: Allure Report action from marketplace
            uses: simple-elf/allure-report-action@master
            if: always()
            with:
              allure_results: allure-results
              allure_history: allure-history
              keep_reports: 20

          - name: Deploy report to Github Pages
            if: always()
            uses: peaceiris/actions-gh-pages@v2
            env:
              PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: allure-history