name: Continuous-Deployment

on:
  workflow_run:
    workflows: ["Continuous-Integration"]
    types:
      - completed
  workflow_dispatch: ~

jobs:
  api-tests:
    uses: ./.github/workflows/Run_api_tests.yml
    with:
      environment: >-
        ["windows-2022", "ubuntu-latest", "macOs-latest"]
      test_results_path: './results'

  web-tests:
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      environment: >-
        ["windows-2022"]
      driver_type: >-
        ["Chrome", "Firefox", "Edge"]
      test_results_path: './results'

  desktop-tests:
    uses: ./.github/workflows/Run_desktop_tests.yml
    with:
      environment: >-
        ["windows-2022", "windows-2019"]
      test_results_path: './results'

  android-tests:
    uses: ./.github/workflows/Run_appium_tests.yml
    with:
      environment: >-
        ["ubuntu-latest"]
      test_results_path: './results'
