name: Continuous-Delivery

on: workflow_dispatch
  push:
    branches:
      - main

jobs:
  test:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-api
      - name: Run tests
        run: dotnet test TestWare.Samples.API.dll
