name: Continuous-Deployment

on:
  workflow_run:
    workflows: ["Continuous-Integration"]
    types:
      - completed
  workflow_dispatch: ~

jobs:
  api-tests:
    uses: ./.github/workflows/Run_api_tests.yml
    with:
      environment: >-
        ["windows-2022", "ubuntu-latest", "macOs-latest"]
      test_results_path: './results'

  web-tests:
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      environment: >-
        ["windows-2022"]
      driver_type: >-
        ["Chrome", "Firefox", "Edge"]
      test_results_path: './results'

  desktop-tests:
    uses: ./.github/workflows/Run_desktop_tests.yml
    with:
      environment: >-
        ["windows-2022", "windows-2019"]
      test_results_path: './results'

  android-tests:
    uses: ./.github/workflows/Run_appium_android_tests.yml
    with:
      environment: >-
        ["macOs-latest"]
      test_results_path: './results'

  ios-tests:
    uses: ./.github/workflows/Run_appium_ios_tests.yml
    with:
      environment: >-
        ["macOs-latest"]
      test_results_path: './results'
      
  allure-results:
    needs: 
        - api-tests
        - web-tests
        - desktop-tests
        - android-tests
        - ios-tests
    if: always()
    uses: ./.github/workflows/Allure_Report.yml
      
  publish-test-results:
    needs: 
        - api-tests
        - web-tests
        - desktop-tests
        - android-tests
        - ios-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: results-*
          path: results
      - name: Publish Summary Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "results/**/*.trx"
