name: Continuous-Integration

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  build:
    name: Create Testing Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Archive Testing artifacts - API
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-api
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.API/bin/Release/net6.0
      - name: Archive Testing artifacts - Appium Mobile
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-appium-mobile
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.Appium.Mobile/bin/Release/net6.0
      - name: Archive Testing artifacts - Selenium Web
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-selenium-web
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.Selenium.Web/bin/Release/net6.0
      - name: Archive Testing artifacts - WinAppDriver
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-winappdriver
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.WinAppDriver/bin/Release/net6.0

  test-api:
    needs: build
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-api
      - name: Run tests
        run: dotnet test TestWare.Samples.API.dll

  test-chrome:
    name: Run WEB (Chrome) tests
    needs: build
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      driver_type: 'Chrome'
      test_results_path: 'C:\workspace\ERNI\results'

  test-edge:
    name: Run WEB (Edge) tests
    needs: build
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      driver_type: 'Edge'
      test_results_path: 'C:\workspace\ERNI\results'

  test-firefox:
    name: Run WEB (Firefox) tests
    needs: build
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      driver_type: 'Firefox'
      test_results_path: 'C:\workspace\ERNI\results'

  test-ie:
    name: Run WEB (IE) tests
    needs: build
    uses: ./.github/workflows/Run_web_tests.yml
    with:
      driver_type: 'InternetExplorer'
      test_results_path: 'C:\workspace\ERNI\results'
