name: Continuous-Integration

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  build:
    name: Create Testing Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Archive Testing artifacts - API
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-api
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.API/bin/Release/net6.0
      - name: Archive Testing artifacts - Appium Mobile
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-appium-mobile
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.Appium.Mobile/bin/Release/net6.0
      - name: Archive Testing artifacts - Selenium Web
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-selenium-web
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.Selenium.Web/bin/Release/net6.0
      - name: Archive Testing artifacts - WinAppDriver
        uses: actions/upload-artifact@v2
        with:
          name: testing-artifact-winappdriver
          path: |
            ${{ github.workspace }}/samples/TestWare.Samples.WinAppDriver/bin/Release/net6.0

  test-api:
    needs: build
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-api
      - name: Run tests
        run: dotnet test TestWare.Samples.API.dll

  test-chrome:
    needs: build
    name: Run WEB (Chrome) tests
    runs-on: windows-2022
    steps:
      - uses: ./.github/workflows/Run_web_tests.yml
        with:
          driver_path: 'C:\SeleniumWebDrivers\ChromeDriver'
          driver_type: 'Chrome'
          test_results_path: 'C:\workspace\ERNI\results'

  test-edge:
    needs: build
    name: Run WEB (Edge) tests
    runs-on: windows-2022
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-selenium-web
      - name: Replace Driver at TestConfiguration.json
        shell: pwsh
        run: |
          $driverPath = "C:\SeleniumWebDrivers\EdgeDriver".Replace("\","\\")

          $content = '{
            "Configurations": [
              {
                "Tag": "WebDriver",
                  "Capabilities": [
                      {
                          "Name": "WebDriver",
                          "Path": "' + $driverPath + '",
                          "Driver": "Edge",
                          "CommandTimeOutInMinutes": 5,
                          "Arguments": [
                              "--start-maximized"
                          ]
                      }
                  ]
              }
            ],
            "TestResultPath": "C:\\workspace\\ERNI\\results\\"
          }'

          Set-Content -Path '.\TestConfiguration.Web.json' -Value $content
      - name: Run tests
        run: dotnet test TestWare.Samples.Selenium.Web.dll
      - name: Archive WEB (Edge) screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: web-edge-screenshots
          path: |
            C:\workspace\ERNI\results\

  test-firefox:
    needs: build
    name: Run WEB (Firefox) tests
    runs-on: windows-2022
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-selenium-web
      - name: Replace Driver at TestConfiguration.json
        shell: pwsh
        run: |
          $driverPath = "C:\SeleniumWebDrivers\GeckoDriver".Replace("\","\\")

          $content = '{
            "Configurations": [
              {
                "Tag": "WebDriver",
                  "Capabilities": [
                      {
                          "Name": "WebDriver",
                          "Path": "' + $driverPath + '",
                          "Driver": "Firefox",
                          "CommandTimeOutInMinutes": 5,
                          "Arguments": [
                              "--start-maximized"
                          ]
                      }
                  ]
              }
            ],
            "TestResultPath": "C:\\workspace\\ERNI\\results\\"
          }'

          Set-Content -Path '.\TestConfiguration.Web.json' -Value $content
      - name: Run tests
        run: dotnet test TestWare.Samples.Selenium.Web.dll
      - name: Archive WEB (Firefox) screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: web-firefox-screenshots
          path: |
            C:\workspace\ERNI\results\

  test-ie:
    needs: build
    name: Run WEB (IE) tests
    runs-on: windows-2022
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: testing-artifact-selenium-web
      - name: Replace Driver at TestConfiguration.json
        shell: pwsh
        run: |
          $driverPath = "C:\SeleniumWebDrivers\IEDriver".Replace("\","\\")

          $content = '{
            "Configurations": [
              {
                "Tag": "WebDriver",
                  "Capabilities": [
                      {
                          "Name": "WebDriver",
                          "Path": "' + $driverPath + '",
                          "Driver": "InternetExplorer",
                          "CommandTimeOutInMinutes": 5,
                          "Arguments": [
                              "--start-maximized"
                          ]
                      }
                  ]
              }
            ],
            "TestResultPath": "C:\\workspace\\ERNI\\results\\"
          }'

          Set-Content -Path '.\TestConfiguration.Web.json' -Value $content
      - name: Run tests
        run: dotnet test TestWare.Samples.Selenium.Web.dll
      - name: Archive WEB (IE) screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: web-IE-screenshots
          path: |
            C:\workspace\ERNI\results\
