name: Run-desktop-tests

on:
  workflow_call:
    inputs:
      test_results_path:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  desktop-tests:      
      strategy:
        matrix:
          os: ${{fromJson(inputs.environment)}}
        fail-fast: false

      name: Run DESKTOP (${{ matrix.os }}) tests
      runs-on: ${{ matrix.os }}

      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - uses: dawidd6/action-download-artifact@v3.1.4
          with:
            workflow: CI.yml
            name: testing-artifact-winappdriver
        - name: Run git init
          run: git init
        - name: Install Appium Server
          run: |
            npm install -g appium --unsafe-perm=true --allow-root
            appium -v
        - name: Install WinAppDriver driver
          run: |
            appium driver install --source=npm appium-windows-driver
        - name: Run Appium Server
          run: cmd /c "start appium --log ${{ inputs.test_results_path }}/appium.log"
          shell: cmd
        - name: Healthcheck appium
          id: AppiumStatus
          uses: fjogeleit/http-request-action@master
          with:
            url: 'http://127.0.0.1:4723/status'
            method: 'GET'
        - name: Show Response
          run: echo "${{ steps.AppiumStatus.outputs.response }}"
          continue-on-error: true
        - name: config replacement
          uses: microsoft/variable-substitution@v1 
          with:
            files: '.\TestConfiguration.Desktop.json'
          env:
            TestResultPath: ${{ inputs.test_results_path }}
        - name: Run tests
          run: dotnet test TestWare.Samples.WinAppDriver.Desktop.dll --logger "trx;LogFileName=results.trx" --results-directory "${{ inputs.test_results_path }}"  --filter TestCategory!=WindowsCalculator
        - name: Archive DESKTOP (${{ matrix.os }}) screenshots
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: desktop-${{ matrix.os }}-screenshots
            path: |
              ${{ inputs.test_results_path }}
        - name: Archive Testing results - DESKTOP
          uses: actions/upload-artifact@v4
          with:
            name: results-DESKTOP-${{ matrix.os }}
            path: ${{ inputs.test_results_path }}/results.trx
        - name: Archive Testing artifacts - Allure
          if: always()
          uses: actions/upload-artifact@v4
          with:
              name: allure-results-DESKTOP-${{ matrix.os }}
              path: '.\allure-results'
