name: Run-desktop-tests

on:
  workflow_call:
    inputs:
      test_results_path:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  web-tests:      
      strategy:
        matrix:
          os: ${{fromJson(inputs.environment)}}
        fail-fast: false

      name: Run DESKTOP (${{ matrix.os }}) tests
      runs-on: ${{ matrix.os }}

      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - uses: actions/download-artifact@v2
          with:
            name: testing-artifact-selenium-web
        - name: Install and Run Appium Server
          uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
        - name: Run tests
          run: dotnet test TestWare.Samples.WinAppDriver.Desktop.dll
        - name: Archive DESKTOP (${{ matrix.os }}) screenshots
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: desktop-${{ matrix.os }}-screenshots
            path: |
              ${{ inputs.test_results_path }}
