name: Run-web-tests

on:
  workflow_call:
    inputs:
      driver_type:
        required: true
        type: string
      test_results_path:
        required: true
        type: string

env:
  DRIVER_PATH: ''

jobs:
  web-tests:
      runs-on: windows-2022
      steps:
        - name: Ubuntu GitHub Actions environment variables List
          run: env

        - run: echo $env:GeckoWebDriver >> >> $DRIVER_PATH
          if: inputs.driver_type == 'Firefox'          
        - run: echo $env:EdgeWebDriver >> >> $DRIVER_PATH
          if: inputs.driver_type == 'Edge'
        - run: echo $env:ChromeWebDriver >> $DRIVER_PATH
          if: inputs.driver_type == 'Chrome'
        - run: echo $env:IEWebDriver >> $DRIVER_PATH
          if: inputs.driver_type == 'InternetExplorer'

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - uses: actions/download-artifact@v2
          with:
            name: testing-artifact-selenium-web
        - name: Replace Driver at TestConfiguration.json
          shell: pwsh
          run: |
            $driverPath = $DRIVER_PATH.Replace("\","\\")
            $testResultsPath = "${{ inputs.test_results_path }}".Replace("\","\\")

            $content = '{
              "Configurations": [
                {
                  "Tag": "WebDriver",
                    "Capabilities": [
                        {
                            "Name": "WebDriver",
                            "Path": "' + $driverPath + '",
                            "Driver": "${{ inputs.driver_type }}",
                            "CommandTimeOutInMinutes": 5,
                            "Arguments": [
                                "--start-maximized"
                            ]
                        }
                    ]
                }
              ],
              "TestResultPath": "' + $testResultsPath + '"
            }'

            Set-Content -Path '.\TestConfiguration.Web.json' -Value $content
        - name: Run tests
          run: dotnet test TestWare.Samples.Selenium.Web.dll
        - name: Archive WEB (${{ inputs.driver_type }}) screenshots
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: web-${{ inputs.driver_type }}-screenshots
            path: |
              ${{ inputs.test_results_path }}
