name: Run-desktop-tests

on:
  workflow_call:
    inputs:
      test_results_path:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  desktop-tests:      
      strategy:
        matrix:
          os: ${{fromJson(inputs.environment)}}
        fail-fast: false

      name: Run DESKTOP (${{ matrix.os }}) tests
      runs-on: ${{ matrix.os }}

      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - uses: actions/download-artifact@v2
          with:
            name: testing-artifact-selenium-web

        - name: Install Appium Server
          run: npm install -g appium
        - name: Run Appium Server
          run: start appium --port 4723    
        - name: Check Appium Server is running
          run: TASKLIST /FI "IMAGENAME eq cmd.exe" /V

        - name: Run tests
          run: dotnet test TestWare.Samples.WinAppDriver.Desktop.dll
        - name: Archive DESKTOP (${{ matrix.os }}) screenshots
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: desktop-${{ matrix.os }}-screenshots
            path: |
              ${{ inputs.test_results_path }}
