name: Run-desktop-tests

on:
  workflow_call:
    inputs:
      test_results_path:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  desktop-tests:      
      strategy:
        matrix:
          os: ${{fromJson(inputs.environment)}}
        fail-fast: false

      name: Run DESKTOP (${{ matrix.os }}) tests
      runs-on: ${{ matrix.os }}

      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
        - uses: LexisNexis-Public-GHA/sbs-action-download-artifact@v2.13.1
          with:
            workflow: CI.yml
            name: testing-artifact-winappdriver

        - name: Install Appium Server
          run: |
            npm install -g appium --unsafe-perm=true --allow-root
            appium -v
        - name: Run Appium Server
          run: start appium --log ${{ inputs.test_results_path }}/appium.log
          shell: cmd
        - name: Sleep for 30 seconds
          run: Start-Sleep -s 30
          shell: powershell
        # - name: Healthcheck appium
        #   id: AppiumStatus
        #   uses: fjogeleit/http-request-action@master
        #   with:
        #     url: 'http://0.0.0.0:4723/wd/hub/status'
        #     method: 'GET'
        # - name: Show Response
        #   run: echo ${{ steps.AppiumStatus.outputs.response }}
        - name: Run Appium Server
          run: start appium --log ${{ inputs.test_results_path }}/appium2.log
          shell: cmd
        - name: Run tests
          run: dotnet test TestWare.Samples.WinAppDriver.Desktop.dll
        - name: Archive DESKTOP (${{ matrix.os }}) screenshots
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: desktop-${{ matrix.os }}-screenshots
            path: |
              ${{ inputs.test_results_path }}
